### ISSUE TITLE
单词显示问题

### ISSUE THREAD

**Issue by oxidegit** [Jolly23/GRE3000#2]
除了前面几个单词，后面显示的都是undefined。

**Comment by Jolly23** [comment]
你好，我没有发现过这个问题，请问可以描述的更清楚一些吗？
登陆状态还是未登陆状态？
你说的问题是在我的网站上还是在你自己编译这个工程中呢？

我猜想问题的原因是json返回的标签和你在前端js里写的不一样，导致的undefined

**Comment by Jolly23** [comment]
@sgyyamn 我刚刚检查了下，在我的网站上发现了问题，未登陆状态下的异步加载单词全部由于json标签的错误导致了undefined，非常抱歉。
问题已修正

ps: 加入webster链接那个版本，测试的时候只在登陆模式下进行了，却忘记在未登陆模式下进行测试，导致这样的低级错误实在不该。
