### ISSUE TITLE
希望能得到您的一点帮助

### ISSUE THREAD

**Issue by oxidegit** [Jolly23/GRE3000#3]
你好，我是民大的一名学生，现在有兴趣开发一个微信公众号，请问您能给我推荐一些资料或者建议吗。

我跟着网上视频做了一点，想在应用部署在新浪SAE服务器上面，微信公众号开发文档里面说需要一个中控服务器来专门处理access-token,现在有点不知道怎么下手的感觉，刚开始接触web开发的一些相关知识，希望不吝赐教，感激不尽。

**Comment by Jolly23** [comment]
AccessToken只是微信平台最基础的一部分，关键是你想要这个平台实现什么功能。
可以邮件联系我，乐意效劳 
zhaolei@protonmail.com
